# Generated by Django 2.2.1 on 2019-06-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer2',
        ),
        migrations.AddField(
            model_name='order',
            name='modify_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='nfs_network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='protocol_scp',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='protocol_sftp',
            field=models.BooleanField(default=True, verbose_name='SFTP'),
        ),
        migrations.AlterField(
            model_name='order',
            name='protocol_ssh',
            field=models.BooleanField(default=True, verbose_name='SSH'),
        ),
        migrations.AlterField(
            model_name='person',
            name='institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
