# Generated by Django 2.2.1 on 2019-06-26 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190605_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='submitter',
        ),
        migrations.CreateModel(
            name='PersonOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ROLE_OWNER', 'ROLE_OWNER'), ('ROLE_HEAD', 'ROLE_HEAD'), ('ROLE_TECH', 'ROLE_TECH')], max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='order.Order')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.Person')),
            ],
        ),
    ]
