# Generated by Django 2.2.1 on 2019-08-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190626_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='persons',
            field=models.ManyToManyField(related_name='order_order_related', related_query_name='order_orders', through='order.PersonOrder', to='order.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='admin',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='orders',
            field=models.ManyToManyField(related_name='order_person_related', related_query_name='order_persons', through='order.PersonOrder', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='group_cifsacls',
            field=models.BooleanField(verbose_name='CIFS ACLs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='nfs_network',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NFS V3 (Client needs to be connected to KIT-IDM)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='protocol_cifs',
            field=models.BooleanField(verbose_name='CIFS'),
        ),
        migrations.AlterField(
            model_name='order',
            name='protocol_nfs',
            field=models.BooleanField(verbose_name='NFS'),
        ),
        migrations.AlterField(
            model_name='order',
            name='protocol_scp',
            field=models.BooleanField(default=True, verbose_name='SCP'),
        ),
    ]
