# Generated by Django 2.2.1 on 2019-08-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190812_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='protocol_scp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='protocol_sftp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='protocol_ssh',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Your comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='group_cifsacls',
            field=models.BooleanField(verbose_name='Extended group permissions (ACLs)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='group_name',
            field=models.CharField(help_text='Which group should get access to your project directory (e.g. OE-ProjectName-LSDF)? Please contact your ITB to create a group.', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='nfs_network',
            field=models.CharField(blank=True, help_text='Has to be one or many IPs or Subnets (for example 141.52.000.0/24)', max_length=50, null=True, verbose_name='NFS Client networks*'),
        ),
        migrations.AlterField(
            model_name='order',
            name='protocol_nfs',
            field=models.BooleanField(verbose_name='NFS V3 (Client needs to be connected to KIT-IDM)'),
        ),
    ]
